'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
'''

#!/bin/python

import sys


t = int(raw_input().strip())
results=[]
for a0 in xrange(t):
    n = long(raw_input().strip())
    f1=1
    f2=2
    sum=0
    x=f2
    while x<=n:
        if x%2==0: 
            sum+=x
        x=(f1 + f2)
        f1=f2
        f2=x
    results.append(sum)
for r in results:
    print(r)